config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'movies', to: 'movies#index_view'
  get 'movies/new', to: 'movies#new_view'
  post 'movies/new', to: 'movies#create'
  get 'movies/admin', to: 'movies#admin_view'
  get 'movies/:id', to: 'movies#show_view', as: 'movie_show_view'
  post 'movies/activate/:id', to: 'movies#activate', as: 'activate_movie'
  post 'movies/remove/:id', to: 'movies#remove', as: 'remove_movie'

  get 'users', to: 'users#current_view'
  get 'users/new', to: 'user_registrations#new_view'
  post 'users/new', to: 'user_registrations#create'
  get 'users/login', to: 'user_sessions#new_view'
  post 'users/login', to: 'user_sessions#create'
  delete 'users/logout', to: 'user_sessions#destroy'
  get 'users/admin', to: 'admin#index_view', as: 'admin'

  get 'rentals', to: 'rentals#index_view'
  get 'rentals/new', to: 'rentals#new_view'
  post 'rentals/new', to: 'rentals#create'
  get 'rentals/active', to: 'rentals#active_view'
  post 'rental/return/:id', to: 'rentals#return_rental', as: 'return_rental'
  delete 'rentals/:id', to: 'rentals#destroy', as:'remove_rental'

  get 'transaction/rate/:id', to: 'ratings#new_view', as:'rate_rental_view'
  post 'transaction/rate/:id', to: 'ratings#create', as:'rate_rental'
  get 'transaction/:id', to: 'rental_transactions#index_view', as: 'transaction_view'

  post 'cart/add/:id', to: 'cart#add_rental_to_cart', as: 'add_to_cart'
  delete 'cart/remove/:id', to: 'cart#remove_rental_from_cart', as: 'remove_from_cart'

  resources :rental_charges, only: [:new, :create]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_user_to_be_admin!, only: [
    :new_view, :create, :admin_view , :remove, :activate
  ]
  before_action :set_movie, only: [
    :show_view, :deactive, :activate, :remove
  
  ]
  def index_view
    @movies = Movie.all
  end

  def show_view
    if !@movie.active
      redirect_to movies
    else
      @rentals = Rental.where(movie: @movie)
    end
  end

  def new_view
  end

  def admin_view
    @movies = Movie.all
  end

  def create
    @movie = Movie.new(
      name: params[:name],
      description: params[:description]
    )
    if @movie.save
      @movie.photo.attach(params[:photo]) 
      flash[:notice] = "Added #{@movie.name} to registry"
      redirect_to movie_show_view_path(@movie)
    else
      flash[:alert] = @movie.errors.full_messages.to_sentence
      redirect_to movies_new_path
    end
  end

  def activate
    @movie.activate
    flash[:notice] = "Activated #{@movie.name}."
    redirect_to admin_path
  end

  def remove
    @movie.remove
    flash[:notice] = "Removed #{@movie.name}"
    redirect_to admin_path
  end


end

app/helpers/movies_helper.rb
module MoviesHelper
  
end

app/views/movies/admin_view.html.erb
<h1>Movies</h1>
<br/>
<br/>

<div class="container">
  <table class="table">
    <thead>
      <th scope="col">Name</th>
      <th scope="col">Rating</th>
      <th scope="col">Reviews</th>
      <th scope="col">Total Rentals</th>
      <th scope="col">DVD Count</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
      
        <tr>
          <td><%= movie.name %></td>
          <td>
            <% if movie.rental_history != 0 %>
              <%= movie.rating %> /10 stars
            <% else %>
              No Rating
            <% end %>
          </td>
          <td><%= movie.rating_count %></td>
          <td><%= movie.rental_history %> </td>
          <td><%= movie.rentals.count %></td>
          <td>
            <% if movie.active %>
              <%= link_to "Remove", remove_movie_path(movie), method: :post, class: "btn btn-danger btn-sm"%>
            <% else %>
              <%= link_to "Activate",  activate_movie_path(movie), method: :post,  class: "btn btn-primary btn-sm"%>
            <% end %>
          </td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    </table>
</div>

app/views/movies/index_view.html.erb
<% @movies.each do |movie| %>
  <% if movie.active %>

      <div class="container border m-3 p-4">
      <div class="inline-box">
        <div style="display: block;">
          <img src="<%= Faker::Placeholdit.image(size: '400x400')  %>"  alt="...">
        </div>
        <div class="container">
          <div class="border-bottom border-dark border-2">
            <h5 class="mx-3"><%= movie.name %> 
              <span class="mx-2"> | 
                <% if movie.rental_history != 0 %>
                  <%= movie.rating %> /10 stars
                <% else %>
                  Not Yet Rated
                <% end %>
             </span> 
            </h5>
          </div>
          <p class="p-2"><%= movie.description %></p>  
          <%= link_to 'Rent Movie', movie_show_view_path(movie.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/movies/new_view.html.erb
<h1>New Movie</h1>

<%= form_with url: movies_new_path do |f| %>
  <div class="row p-3">
    <div class="col">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Movie Name" %>
    </div>

    <div class="col" hidden>
      <%= f.label :photo %>
      <%= f.file_field :photo, accept: "image/*"%>
    </div>
  </div>

  <div class="row p-3">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Movie Description", rows: 12 %>
  </div>

  <div class="row p-3">
    <%= f.submit "Create Movie", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/movies/show_view.html.erb
<div class="border-bottom border-dark border-2 m-2">
  <h2 class="m-3"><%= @movie.name %> 
    <span class="mx-2"> | 
      <% if @movie.rental_history != 0 %>
        <%= @movie.rating %> /10 stars
      <% else %>
        Not Yet Rated
      <% end %>
    </span>
  </h2>  
</div>
<div class="container">
  <div class="row">
    <img src="<%= Faker::Placeholdit.image(size: '500x500')  %>"  alt="..." class="col">
      <div class="col">
        <p class="my-3"><%= @movie.description %></p>  
    </div>
  </div>
</div>


<div class="container m-4">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Condition</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @rentals.each do |rental |%>
          <% if !rental.removed? %>
            <tr>
              <td><%= @movie.name %></td>
              <td><%= rental.condition.capitalize %></td>
              <% if rental.available? %>
                <td><%= link_to 'Add to cart', add_to_cart_path(rental), class: "btn btn-primary", method: :post %></td>
              <% else %>
                <td><a class="btn btn-danger">Checked out</a></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>