config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'movies', to: 'movies#index_view'
  get 'movies/new', to: 'movies#new_view'
  post 'movies/new', to: 'movies#create'
  get 'movies/admin', to: 'movies#admin_view'
  get 'movies/:id', to: 'movies#show_view', as: 'movie_show_view'
  post 'movies/activate/:id', to: 'movies#activate', as: 'activate_movie'
  post 'movies/remove/:id', to: 'movies#remove', as: 'remove_movie'

  get 'users', to: 'users#current_view'
  get 'users/new', to: 'user_registrations#new_view'
  post 'users/new', to: 'user_registrations#create'
  get 'users/login', to: 'user_sessions#new_view'
  post 'users/login', to: 'user_sessions#create'
  delete 'users/logout', to: 'user_sessions#destroy'
  get 'users/admin', to: 'admin#index_view', as: 'admin'

  get 'rentals', to: 'rentals#index_view'
  get 'rentals/new', to: 'rentals#new_view'
  post 'rentals/new', to: 'rentals#create'
  get 'rentals/active', to: 'rentals#active_view'
  post 'rental/return/:id', to: 'rentals#return_rental', as: 'return_rental'
  delete 'rentals/:id', to: 'rentals#destroy', as:'remove_rental'

  get 'transaction/rate/:id', to: 'ratings#new_view', as:'rate_rental_view'
  post 'transaction/rate/:id', to: 'ratings#create', as:'rate_rental'
  get 'transaction/:id', to: 'rental_transactions#index_view', as: 'transaction_view'

  post 'cart/add/:id', to: 'cart#add_rental_to_cart', as: 'add_to_cart'
  delete 'cart/remove/:id', to: 'cart#remove_rental_from_cart', as: 'remove_from_cart'

  resources :rental_charges, only: [:new, :create]
end

app/views/shared/_admin_navbar.html.erb
<%= link_to 'Movies', movies_admin_path, class: "text-light header-item" %>
<%= link_to "Rentals", rentals_path, class: "text-light header-item" %>
<%= link_to 'Active Rentals', rentals_active_path, class: "text-light header-item"  %>
<%= link_to "Admin", admin_path, class: "text-light header-item" %>
<%= link_to "Logout", users_logout_path,method: :delete, class: "text-light header-item" %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-priamry alert-primary alert-dismissible fade show mt-3" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger alert-primary alert-dismissible fade show mt-3" role="alert">
    <%= flash[:alert] %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_logged_in_navbar.html.erb
<%= link_to 'Movies', movies_path, class: "text-light header-item" %>
<%= link_to "My Account", users_path, class: "text-light header-item" %>
<%= link_to 'Cart', new_rental_charge_path, class: "text-light header-item" %>
<%= link_to "Logout", users_logout_path,method: :delete, class: "text-light header-item" %>

app/views/shared/_main.html.erb
<div class="container p-3">
   <%= render partial: "shared/flash"%>
   <div class="p-3">
      <%=  yield %>
   </div>
</div>

<br/>
<br/>

app/views/shared/_navbar.html.erb
<div class="sidebar bg-dark">
  <a href="/" class="text-center">
    <%= image_tag 'RailsRentals-logos_white.png', width: "150", height: "100" %>
  </a>
    

    <% if Current.user.present? && Current.user.client? %>
      <%= render partial: "shared/logged_in_navbar" %>
    <% elsif Current.user.present? && Current.user.admin?%>
      <%= render partial: "shared/admin_navbar" %>
    <% else %>
      <%= render partial: "shared/no_user_navbar" %>
    <% end %>
    <a href="https://github.com/RyanMcTague/Rails-Rentals" class="text-light header-item"> View the Code</a>


</div>

app/views/shared/_no_user_navbar.html.erb
<%= link_to 'Login', users_login_path, class: "text-light header-item" %>
<%= link_to 'Create an Account', users_new_path, class: "text-light header-item" %>