config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'movies', to: 'movies#index_view'
  get 'movies/new', to: 'movies#new_view'
  post 'movies/new', to: 'movies#create'
  get 'movies/admin', to: 'movies#admin_view'
  get 'movies/:id', to: 'movies#show_view', as: 'movie_show_view'
  post 'movies/activate/:id', to: 'movies#activate', as: 'activate_movie'
  post 'movies/remove/:id', to: 'movies#remove', as: 'remove_movie'

  get 'users', to: 'users#current_view'
  get 'users/new', to: 'user_registrations#new_view'
  post 'users/new', to: 'user_registrations#create'
  get 'users/login', to: 'user_sessions#new_view'
  post 'users/login', to: 'user_sessions#create'
  delete 'users/logout', to: 'user_sessions#destroy'
  get 'users/admin', to: 'admin#index_view', as: 'admin'

  get 'rentals', to: 'rentals#index_view'
  get 'rentals/new', to: 'rentals#new_view'
  post 'rentals/new', to: 'rentals#create'
  get 'rentals/active', to: 'rentals#active_view'
  post 'rental/return/:id', to: 'rentals#return_rental', as: 'return_rental'
  delete 'rentals/:id', to: 'rentals#destroy', as:'remove_rental'

  get 'transaction/rate/:id', to: 'ratings#new_view', as:'rate_rental_view'
  post 'transaction/rate/:id', to: 'ratings#create', as:'rate_rental'
  get 'transaction/:id', to: 'rental_transactions#index_view', as: 'transaction_view'

  post 'cart/add/:id', to: 'cart#add_rental_to_cart', as: 'add_to_cart'
  delete 'cart/remove/:id', to: 'cart#remove_rental_from_cart', as: 'remove_from_cart'

  resources :rental_charges, only: [:new, :create]
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :movie
  belongs_to :user, optional: true
  has_many :rental_transactions
  has_many :fines, through: :rental_transactions
  enum state: [:available, :in_cart, :checked_out, :removed]
  has_one :rating
  
  def current_transaction
    if self.user.present?
      return RentalTransaction.find_by(user_id: self.user.id, rental_id: self.id, state: :checked_out)
    else
      return nil
    end
  end

  def fine
    if self.user.present?
      return Fine.find_by(rental_transaction: current_transaction, paid: false)
    else
      return nil
    end
  end

  def pay_fine
    if self.fine.present? 
      fine.update(paid: true)
    end
  end

  def fine_total
    if self.user.present? && self.fine.present?
      return self.fine.amount
    else
      return nil
    end
  end

  def bad_condition?
    return self.condition == 'bad'
  end

  def fair_condition?
    return self.condition == 'fair'
  end

  def new_condition?
    return self.condition == 'new'
  end

  def in_stock?
    return !self.checked_out
  end

  def base_price
    return ENV["RENTAL_COST_PER_PERIOD"].to_f
  end

  def condition_increase
    return ENV["CONDITION_INCREASE"].to_f
  end

  def cost
    if self.bad_condition?
      return (self.base_price ).round(2)
    elsif self.fair_condition?
      return (self.base_price * (1 + self.condition_increase)).round(2)
    else self.bad_condition?
      return (self.base_price * (1 + 2 * self.condition_increase)).round(2)
    end
  end

  def add_to_cart user
    self.update(user_id: user.id, state: :in_cart)
  end

  def remove_from_cart 
    self.update(user_id: nil, state: :available)
  end
  
  def rental_duration
    return ENV['RENTAL_DURATION_IN_DAYS'].to_i.days
  end

  def check_out
    if self.in_cart?
      self.update(state: :checked_out)
      RentalTransaction.create(
        user_id: self.user.id, 
        rental_id: self.id, 
        price: self.cost,
        given_condition: self.condition,
        state: :checked_out,
        due: rental_duration.from_now.beginning_of_day
      )
    end
  end

  def return_to_store 
    if self.checked_out?
      self.current_transaction.update(state: :completed)
      self.update(user_id: nil, state: :available)
    end
  end

  def remove_from_stock
    self.update(state: :removed)
  end 

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :require_user_to_be_admin!
  before_action :set_rental, only: [:destroy, :return_rental]

  
  def index_view
    @rentals = Rental.all
  end

  def active_view
    @transactions = RentalTransaction.where(state: :checked_out).each
    @transactions.each do |transaction|
      transaction.apply_late_fee
    end
  end


  def new_view
    @movie_names = []
    Movie.all.each do |movie|
      @movie_names.append(movie.name)
    end
  end

  def create
    amount = params[:quantity].to_i
    amount.times do
      @rental = Rental.create(
        condition: params[:condition].downcase,
        movie: Movie.find_by(name: params[:movie_name]),
      )
    end
    flash[:notice] = "Created rental(s)"
    redirect_to admin_path
  end

  def destroy
    @rental.remove_from_stock
    flash[:notice] = "Rental successfully removed"
    redirect_to admin_path
  end

  def return_rental
    @rental.return_to_store
    flash[:notice] = "Returned rental to store!"
    redirect_to admin_path
  end



end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/active_view.html.erb
<div class="container mt-4">
  <h4 class="m-4">Current Rented Movies</h4>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Name</th>
        <th scope="col">Rental ID</th>
        <th scope="col">Status</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% @transactions.each do |transaction| %>
      <% rental = transaction.rental %>
      <% if rental.checked_out? %>
        <% if transaction.due_today? %>
          <tr class="table-warning">
            <td><%= rental.user.email  %></td>
            <td><%= rental.movie.name %></td>
            <td><%= rental.id %></td>
            <td>
              <% if transaction.overdue? %>
                Overdue
              <% else %>
                -
              <% end %>
            </td>
            <td><%= link_to "View", transaction_view_path(transaction), class: "btn btn-primary btn-sm"%></td>
          </tr> 
        <% elsif transaction.overdue? %>
          <tr class="table-danger">
            <td><%= rental.user.email  %></td>
            <td><%= rental.movie.name %></td>
            <td><%= rental.id %></td>
            <td>
              <% if transaction.overdue? %>
                Overdue
              <% else %>
                -
              <% end %>
            </td>
            <td><%= link_to "View", transaction_view_path(transaction), class: "btn btn-primary btn-sm"%></td>
          </tr>
        <% else %>
          <tr>
            <td><%= rental.user.email %></td>
            <td><%= rental.movie.name %></td>
            <td><%= rental.id %></td>
            <td>
              <% if transaction.overdue? %>
                Overdue
              <% else %>
                -
              <% end %>
            </td>
            <td><%= link_to 'View', transaction_view_path(transaction.id), class: "btn btn-primary btn-sm" %></td>
          </tr> 
        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>


</div>

app/views/rentals/index_view.html.erb
<div class="container mt-4">
  <h4 class="m-4">All Rentals</h4>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Movie</th>
        <th scope="col">Rental ID</th>
        <th scope="col">Condition</th>
        <th scope="col">State</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @rentals.each do |rental| %>
    <% if !rental.removed? %>
       <% if rental.bad_condition? %>
        <tr class="table-danger">
          <td><%= rental.movie.name %></td>
          <td><%= rental.id %></td>
          <td><%= rental.condition %></td>
          <td><%= rental.state %></td>
          <td>
            <% if !rental.checked_out? %>
              <%= link_to 'Remove', remove_rental_path(rental), method: :delete, class: "btn btn-sm btn-danger"  %>
            <% end %>
          </td>
        </tr>
      <% elsif rental.fair_condition?%>
        <tr class="table-warning">
          <td><%= rental.movie.name %></td>
          <td><%= rental.id %></td>
          <td><%= rental.condition %></td>
          <td><%= rental.state %></td>
          <td>
            <% if !rental.checked_out? %>
              <%= link_to 'Remove', remove_rental_path(rental), method: :delete, class: "btn btn-sm btn-danger"  %>
            <% end %>
          </td>
        </tr>
      <% else %>
        <tr>
          <td><%= rental.movie.name %></td>
          <td><%= rental.id %></td>
          <td><%= rental.condition %></td>
          <td><%= rental.state %></td>
          <td>
            <% if !rental.checked_out? %>
              <%= link_to 'Remove', remove_rental_path(rental), method: :delete, class: "btn btn-sm btn-danger"  %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <% end %>
    </tbody>
  </table>


</div>

app/views/rentals/new_view.html.erb
<h1>New Rental</h1>
<br/>
<br/>
<div class="container">

<%= form_with url: rentals_new_path do |f| %>
  <div class="row p-3">
    <div class="col ">
    <%= f.label "Movie",class: "me-3"%>
    <%= f.select :movie_name, @movie_names %>
    </div>
    <div class="col">
      <%= f.label :condition ,class: "me-3"%>
      <%= f.select :condition, ["New", "Fair", "Bad" ] %>
    </div>
  </div>


  <div class="row p-3">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, min: 1, value: 1 %>
  </div>
  
  <div class="row p-3">
    <%= f.submit "Create Rental(s)", class: "btn btn-primary"%>
  </div>
<% end %>
</div>